### ISSUE TITLE
Is brick:feeds a owl:TransitiveProperty?

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/brick-owl-dl#15]
As we discussed before, I'd like to clarify this issue before we release the next version. 

In @gtfierro's proposal, ``brick:feeds    rdf:type    owl:TransitiveProperty``. (This is not included in the current code base, but he and I had an offline discussion.)

However, I argue it is not.

TransitiveProperty's [definition](https://www.w3.org/TR/owl-ref/#TransitiveProperty-def) is that a->b->c implies a->c. An obvious example is ``brick:isPartOf``. A room is a part of a floor, and the floor is a part of a building. The constitutional relationship does not change even if we omit the intermediate node, the floor.

On the contrary, the context of ``feeds`` changes along with the connections. A common example is that an AHU feeds a VAV, which feeds a Zone. With the transitivity assumption, the example also means that the AHU feeds the Zone. (and ->Economizer->...) However, the physical properties of the Air changes across AHU->VAV->Zone->Economizer->AHU. The AHU cools down the air or heats up the air. A VAV just receives it but the air exhausted from the VAV's Zone would be heated up or cooled down. I expect people would interpret ``feeds`` as its physical function meaning the movements of particles. The particles' properties change down the road. 

An app countered by the concept of ``feeds``'s transitivity is an automated FDD app. The app might want to simply check if all the Air Temperature points at the devices that an AHU feeds have a strong correlation with the AHU's DischargeAir. Otherwise, there should be some leakage in the feeding connections. This is simply an app showing that applying transitivity to ``feeds`` would be counter-intuitive to people. 

If there is any need for transitivity in an app's query, it can be simply done by ``brick:feeds*`` in SPARQL (or something similar in other graph query languages.) If we assume the transitivity, we now cannot preserve the physical meaning of feeds. If transitivity is necessary, a querier may use transitive query using * operator.

Moreover, I do not see any value out of inferring transitive ``feeds`` relationships either in the modeling process and the querying process. 

Hence, I want to remove the transitivity of ``feeds`` in Brick standard relationships.

**Comment by gtfierro** [comment]
I want to make sure I understand and organize the reasons against making `feeds` a transitive relationship. Let me know if I've misunderstood anything or if this is incomplete.

**Claim 1**: The meaning of `feeds` is inconsistent along a chain of `feeds` relationships.

In the chain:

```
AHU --feeds-->  VAV --feeds-->  Zone  (--feeds--> Economizer --feeds--> AHU)
```

each of the nodes is passing "air" along, but they may or may not affect the properties of that air.
An AHU may cool the air down, a VAV may heat the air up, an economizer will heat up the air, etc.

Whether or not this is the responsibility of `feeds`, we would like a way to capture the behavior of equipment as it pertains to the process(es) that the equipment belongs to: how does an AHU affect air, etc.

*Note: this may be addressed by subproperties of `feeds` such as `feedsAir` and by properties of equipment such as `VAV heats air`*

---

**Claim 2**: making `feeds` transitive confuses the notions of "upstream" and "downstream" when there are cycles.

Again, in the chain:

```
AHU --feeds-->  VAV --feeds-->  Zone  (--feeds--> Economizer --feeds--> AHU)
```

the VAV, Zone and Economizer are all both upstream *and* downstream of the AHU, which may feel unintuitive to users and makes it difficult (impossible?) to query for nodes that are 1-hop, 2-hop, *n*-hops away.

Whether or not this is the responsibility of `feeds`, we would like a way to capture the notions of "upstream" and "downstream".

*Note: it feels like bad practice to rely upon number of hops for the correct behavior of an application*

---

**Claim 3**: making `feeds` transitive is redundant with the use of SPARQL 1.1 property paths, e.g. `feeds*`, which can traverse arbitrary numbers of edges.

**Comment by jbkoh** [comment]
You got them right. Thanks for the organization.

I think the decision point, in general, is **whether people would assume the transitivity in modeling/querying or not in their mental models**. So the question is what people would expect this query returns. 

### The query:
```sparql
select ?entity where {
  ex:AHU-1 brick:feeds ?entity.
}
```

### The possible answers with transitivity:
``VAV-1``, ``VAV-2``, ``ZN-1``, ``ZN-2``, ``Econ-1``, ``AHU-1``.

### The possible answers without transitivity:
``VAV-1``, ``VAV-2``.

Even with transitivity, we may produce the second answer by complementing the query with more descriptions about the pattern like using ``heatsAir``, etc. (putting aside a doubt whether it's even doable or not.) However, it should not be counterintuitive to the mental model of modelers/queriers. I interpret ``feeds`` as a physical connection (represented by its feeding function), which makes the multiple hops meaningful. I would not say my interpretation is generalizable to all the users and that's why I wanted to publicly discuss this for learning others' thoughts along with the thought line.

**Comment by gtfierro** [comment]
On the contrary, I don't think the user's mental model fits into this at all. The question we need to answer is how to appropriately model the `feeds` relationship so that we can author the applications we need to. The mental models of users can be addressed through documentation. It is more important to have a clear, unambiguous definition of `feeds` and how it is intended to be used and queried.

I agree that a physical connection is not transitive, but I think your interpretation of `feeds` is incongruent with how we've been using it. `feeds` indicates a *logical* association between two entities where the subject is upstream of the object in the context of some process. An AHU is upstream of a VAV and a VAV is upstream of an HVAC zone in the context of an air circulation loop; `feeds` indicates the direction of the loop.

Making `feeds` transitive gives us a powerful way of modeling these types of processes at different levels of detail. An AHU is *logically* upstream of a Zone in the context of an air circulation loop. This is true even though the AHU is not (directly) physically connected to the vent that actually exfiltrates the air into the zone. Keeping `feeds` logical and transitive means that we can introduce additional entities into this air circulation loop without changing the query.

---

What this discussion suggests to me is that we need a relationship that explicitly denotes a physical connection between two entities. This relationship (for example, something like `isConnectedTo` or `plugsInto`) would not be transitive.

**Comment by jbkoh** [comment]
The logical relationship is based on physical/functional relationships. If its meaning deviates from the physical/functional relationships too much, it will become confusing. 

And yes, ``feeds`` indicates the direction of the loop. Once ``feeds`` becomes transitive, it will lose the directions. AHU--feeds-->VAV and VAV--feeds-->AHU at the same time; there is no direction here.

Everything we want to do, like your example to identify the upstream of a Zone, is possible either with or without the transitivity. All that matters is if the model matches to the actual users' mental models. We can provide documentation as much as needed, but it does not mean that we can deviate from the common understanding of the world. Such deviation will cause inconsistency in the modeling and the querying.

---
I said physical connections but not necessarily meant it. I rather wanted to say **functional** relationships. ``isConnectedTo`` should mean an AHU is connected to a Duct, and the Duct is connected to a VAV, etc. A VAV is not (directly) connected to an AHU.

What is an AHU's function? I'd say it's feeding enough temperature-controlled air to its connected equipment (or locations directly.) And the equipment receiving the fed air has some function to do with the air such as control the flow rate to feed to the zone, etc.

**Comment by gtfierro** [comment]
You are omitting that `feeds` loses the notions of upstream and downstream *only when there is a loop*. If someone creates a loop, then this is expected and predictable behavior.

I'm ok with removing the Transitive property from `feeds` in this prototype, but not for the reasons you've given ( I still disagree that the user's mental model has anything to do with this; we are modeling the semantics of the process, not whatever application-specific, simplified and overfitted impression the user has). We haven't had `feeds` as transitive in previous releases, and changing that would warrant a backwards-incompatible change and hence a bump in major version number. I don't that's appropriate yet, so lets preserve the semantics for now.

**Comment by jbkoh** [comment]
~~Yes, I recognize that this is a bump to the previous version. I think we (or just I) did not correctly understand the meaning of transitivity when we first designed the Brick first version like we did not carefully consider subclass relationships before. I would like to correct the design as soon as possible before having a major release to the public (i.e., forming the consortium.) I don't expect there would be many people out there who have used ``feeds`` assuming the transitivity. We can remove it in the beta version (once we have an agreement) and get the community review before the final release to measure how the version bump affects people out there.~~
Oops, I thought we encoded ``feeds`` was transitive in the previous version, but it was just in the papers.

Loops will be common in ``feeds`` relationships, as something that is fed would not just accumulate somewhere. I believe our design should be useful (and of course correct) over common cases.

Another result by ``feeds``' transitivity is ``VAV1--feeds-->VAV2`` under the air loop. I do not think this is commonly acceptable. ``feeds``'s transitivity could be applied only when the user explicitly wants it.

**Comment by gtfierro** [comment]
Distinguishing between different flows when the `feeds` network should be possible even when the network isn't a DAG, but it is much more complex than just using a single property. We will probably need to use something like `rdf:list` to store edges in a flow. Definitely for future work, but not something we should tackle for the 1.1.0 release
